### ISSUE TITLE
actualactual function issues

### ISSUE THREAD

**Issue by jesusmramirez** [miradulo/isda_daycounters#2]
Why don't you use datetime.datetime(start_year, 1, 1) and use datetime.date.  I got errors when I call this function as it is (a couple of lines below there is something similar).

**Comment by miradulo** [comment]
Hey! Glad  you found this.

Honestly I wrote this a while ago so I'm not sure, but I probably just didn't think anyone would use it with `datetime.datetime`s - that seems reasonable though. 

Thankfully it looks like the only function that has to change for everything to support `datetime.datetime` is `actualactual` as you found. Just have to bring everything to `datetime.datetime`s to make sure the comparisions will work. 

```python
def year_fraction(start_date, end_date):
    """Returns fraction in years between start_date and end_date, using Actual/Actual convention"""
    if start_date == end_date:
        return 0.0

    start_date = dt.datetime.combine(start_date, dt.datetime.min.time())
    end_date = dt.datetime.combine(end_date, dt.datetime.min.time())
    
    start_year = start_date.year
    end_year = end_date.year
    year_1_diff = 366 if calendar.isleap(start_year) else 365
    year_2_diff = 366 if calendar.isleap(end_year) else 365

    total_sum = end_year - start_year - 1
    diff_first = dt.datetime(start_year + 1, 1, 1) - start_date
    total_sum += diff_first.days / year_1_diff
    diff_second = end_date - dt.datetime(end_year, 1, 1)
    total_sum += diff_second.days / year_2_diff

    return total_sum
```

I committed that now, let me know if you have any more issues or suggestions!
